name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      backend:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        ports:
          - 8000:80
        options: >-
          --health-cmd "curl --fail http://localhost:80/tenders || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

