name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      backend:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
        ports:
          - 8000:80
        options: >-
          --health-cmd "curl --fail http://localhost:80/tenders || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

      frontend:
        image: node:18
        ports:
          - 3000:3000
        options: >-
          --health-cmd "curl --fail http://localhost:3000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        working-directory: /app
        command: sh -c "npm install && npm run start"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Vent lidt for at sikre, at backend og frontend er klar
      - name: Wait for servers
        run: sleep 15

      # Installer Playwright og browsere
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      # Sæt miljøvariabel for frontend URL
      - name: Set environment variables
        run: echo "FRONTEND_URL=http://localhost:3000" >> $GITHUB_ENV

      # Kør Playwright-tests headless
      - name: Run Playwright tests
        run: xvfb-run npx playwright test
