name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installer backend dependencies (tilpas til dine requirements)
      - name: Install Python dependencies
        run: |
          pip install fastapi uvicorn pydantic

      # Start backend
      - name: Start backend
        run: |
          cd backend
          uvicorn app:app --host 0.0.0.0 --port 8000 &
          cd ..
        # Antager backend ligger i /backend folder

      # Installer serve globalt
      - name: Install serve
        run: npm install -g serve

      # Start frontend med serve
      - name: Start frontend
        run: |
          serve frontend -l 3000 &
        # Antager frontend ligger i /frontend folder

      # Vent på serverne er klar
      - name: Wait for servers
        run: |
          npx wait-on http://localhost:8000/tenders http://localhost:3000 --timeout 60000

      # Installer Playwright
      - name: Install Playwright
        run: |
          npm install -D @playwright/test
          npx playwright install --with-deps chromium

      # Kør tests
      - name: Run Playwright tests
        run: npx playwright test

      # Upload resultater ved fejl
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7